# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/danai',
                'doc_host': 'https://dangraf.github.io',
                'git_url': 'https://github.com/dangraf/danai',
                'lib_path': 'danai'},
  'syms': {'danai.core': {'danai.core.foo': ('core.html#foo', 'danai/core.py')}}}
